language: elixir
elixir:
  - 1.0.2
otp_release:
  - 17.4
services: mysql
sudo: false # to use faster container based build environment
env:
  - ELIXIR_ERL_OPTIONS=""
  - ELIXIR_ERL_OPTIONS="+T 9"
script:
  - mix test.all
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - eric.meadows.jonsson@gmail.com
